powerData<-read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
powerSubData<-subset(powerData, powerData$Date=="1/2/2007" | powerData$Date=="2/2/2007")
datetime<-strptime(paste(powerSubData$Date, powerSubData$Time, sep = " "), "%d/%m/%Y %H:%M:%OS")
png("plot2.png", width = 480, height = 480)
plot(datetime, as.numeric(powerSubData$Global_active_power), type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()